<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgeLib.Scripting.Assembly\AgeLib.Scripting.Assembly.csproj" />
    <ProjectReference Include="..\AgeLib.Scripting.Compilation\AgeLib.Scripting.Compilation.csproj" />
    <ProjectReference Include="..\AgeLib.Scripting.Script\AgeLib.Scripting.Script.csproj" />
  </ItemGroup>

</Project>
