<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <PublishAot>true</PublishAot>
    <NativeLib>Shared</NativeLib>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishDir>$(MSBuildProjectDirectory)\dist\$(Configuration)\</PublishDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Iced" Version="1.21.0" />
    <ProjectReference Include="..\AgeLib.Engine\AgeLib.Engine.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>