using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AgeLib.Common.Enums;

public enum ObjectData
{
    ID, TYPE, CLASS, CATEGORY, CMDID, ACTION, ORDER, TARGET, POINT_X, POINT_Y, HITPOINTS,
    MAXHP, RANGE, SPEED, DROPSITE, RESOURCE, CARRY, GARRISONED, GARRISON_COUNT, STATUS, PLAYER,
    ATTACK_STANCE, ACTION_TIME, TARGET_ID, FORMATION_ID, PATROLLING, STRIKE_ARMOR, PIERCE_ARMOR,
    BASE_ATTACK, LOCKED, GARRISON_ID, TRAIN_COUNT, TASKS_COUNT, ATTACKER_COUNT, ATTACKER_ID,
    UNDER_ATTACK, ATTACK_TIMER, POINT_Z, PRECISE_X, PRECISE_Y, PRECISE_Z, RESEARCHING, TILE_POSITION,
    TILE_INVERSE, DISTANCE, PRECISE_DISTANCE, FULL_DISTANCE, MAP_ZONE_ID, ON_MAINLAND, IDLING,
    MOVE_X, MOVE_Y, PRECISE_MOVE_X, PRECISE_MOVE_Y, RELOAD_TIME, NEXT_ATTACK, TRAIN_SITE,
    TRAIN_TIME, BLAST_RADIUS, BLAST_LEVEL, PROGRESS_TYPE, PROGRESS_VALUE, MIN_RANGE, TARGET_TIME, HERESY,
    FAITH, REDEMPTION, ATONEMENT, THEOCRACY, SPIES, BALLISTICS, GATHER_TYPE, LANGUAGE_ID, GROUP_FLAG,
    HERO_FLAGS, HERO, AUTO_HEAL, NO_CONVERT, FRAME_DELAY, ATTACK_COUNT, TO_PRECISE, BASE_TYPE, UPGRADE_TYPE,
    OWNERSHIP, CAPTURE_FLAG
}